### PR TITLE
fix(panel): safely access state in mapStateToCanRefine

### LINKED ISSUE #874: Cannot read property 'count' of undefined on refinement components
**Bug 🐞**

### What is the current behavior?
Console error is shown "Cannot read property 'count' of undefined" for every refinement component since last version. Component works as expected though.

Error in callback for watcher "state": "TypeError: Cannot read property 'count' of undefined"
 
### Make a sandbox with the current behavior
https://codesandbox.io/s/nice-ives-16unm?file=/src/App.vue

### What is the expected behavior?
No error should show up in the console.

### Does this happen only in specific situations?
No.

### What is the proposed solution?
-

### What is the version you are using?
v3.4.1

### PR DESCRIPTION
**Pull request by Haroenv**
Most of the widgets were assuming the shape of state is always "right", but since #871 it is also called with an empty object. This PR does the following things:

- changes all widgets to work correctly with empty object
- makes sure always a boolean is returned from mapStateToCanRefine to make tests easier
- make tests of mapStateToCanRefine consistent, as well as adding a unit test to each of the methods using `{}` as state

closes #875 
fixes #874

### CODE REVIEW

File: src/components/__tests__/__snapshots__/RefinementList.js.snap [hunk 1]
```diff
@@ -2,7 +2,7 @@
 
 exports[`allows search bar classes override when it's searchable 1`] = `
 
-<div class="ais-RefinementList ais-RefinementList--noRefinement">
+<div class="ais-RefinementList">
```
Comment (Haroenv) [inline src/components/__tests__/__snapshots__/RefinementList.js.snap:5]: this is because the test used to be wrong (didn't pass `canRefine` in defaultState)

File: src/components/__tests__/Menu.js [hunk 2]
```diff
@@ -313,27 +313,27 @@ describe('default render', () => {
...
-    });
+  expect(mapStateToCanRefine()).toBe(true);
 
-    expect(mapStateToCanRefine()).toBe(false);
+  wrapper.setData({
+    state: {
+      canRefine: false,
+    },
   });
+
```
Comment (eunjae-lee) [inline src/components/__tests__/Menu.js:335]:
```suggestion
     expect(mapStateToCanRefine()).toBe(false); 
```

I guess this was deleted by accident?

**Review by eunjae-lee — APPROVED** [review]
Looks good to me 🙌

File: src/components/__tests__/Menu.js (hunk 2 above)
Comment (Haroenv) [reply src/components/__tests__/Menu.js:335]: yep, thanks!

**Review by yannickcr — APPROVED** [review]

File: src/components/__tests__/Menu.js [hunk 3]
```diff
@@ -313,27 +313,27 @@ describe('default render', () => {
...
+  expect(mapStateToCanRefine()).toBe(true);
 
-    expect(mapStateToCanRefine()).toBe(false);
+  wrapper.setData({
+    state: {
+      canRefine: false,
+    },
   });
+     expect(mapStateToCanRefine()).toBe(false); 
+  expect(wrapper.vm.mapStateToCanRefine({})).toBe(false);
```
Comment (Haroenv) [inline src/components/__tests__/Menu.js:336]:
```suggestion
  expect(mapStateToCanRefine()).toBe(false);

  expect(wrapper.vm.mapStateToCanRefine({})).toBe(false);
```
