### PR TITLE
fix(highlight): don't remove whitespace-only nodes

### LINKED ISSUE #826: ais-highlight removes spaces
**Bug 🐞**

### What is the current behavior?
When typing in the search-box, ais-highlight removes spaces between consecutive words.

2020-07-31 08 14 12 vue-instantsearch netlify app 5327eff91408

### Make a sandbox with the current behavior
https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/vue-instantsearch

### What is the expected behavior?
Spaces between highlighted words should remain.

### What is the version you are using?
3.1.0

### PR DESCRIPTION
**Pull request by Haroenv**
Vue by default removes nodes which are just whitespace: https://github.com/vuejs/vue/blob/ec78fc8b6d03e59da669be1adf4b4b5abf670a34/dist/vue.common.dev.js#L2527

We need to prevent this, since sometimes between highlights, there is just a space, we need to make the value not "wrapped". We can't make the value always "block" (i don't know the correct name for this), since that would add spaces between "inline" highlights.

fixes #826

### CODE REVIEW

File: src/components/Highlighter.vue [hunk 1]
```diff
@@ -40,7 +40,7 @@ export default {
         functional: true,
         render(createElement, context) {
           const slots = context.slots();
-          return slots.default;
+          return slots.default || ' ';
```
Comment (Haroenv) [inline src/components/Highlighter.vue:43]:
```suggestion
          return slots.default;
```

this doesn't work (cry cry)

File: src/components/Highlighter.vue [hunk 2]
```diff
@@ -1,13 +1,13 @@
...
+  <span :class="suit()">
     <component
       v-for="({ value, isHighlighted }, index) in parsedHighlights"
       :class="[isHighlighted && suit('highlighted')]"
       :key="index"
       :is="isHighlighted ? highlightedTagName : textNode"
-    >{{ value }}</component>
+    ><template v-if="value === ' '">
+      {{ value }}
+    </template><template v-else>{{ value }}</template></component>
```
Comment (eunjae-lee) [inline src/components/Highlighter.vue:10]: I'm having a hard time understanding this even after reading your summary. Can you help me a little bit? How is `v-if` different from `v-else`?

Comment (Kocal) [reply src/components/Highlighter.vue:10]: It is different due to how white spaces are handled in the first block and the second block, 
image

Comment (Haroenv) [reply src/components/Highlighter.vue:10]: Thanks @Kocal, indeed the difference is in the form. If text or moustache is directly without space to a tag, it will be rendered without wrapping spaces, however if it's on a newline, whitespace-only blocks will be preserved.

see https://github.com/vuejs/vue/issues/9208

Comment (Haroenv) [reply src/components/Highlighter.vue]: I've just changed it slightly  to make the difference more clear

leading & trailing whitespace | before this PR
---|---
Screenshot 2020-07-31 at 13 41 18 | Screenshot 2020-07-31 at 13 41 01

Comment (eunjae-lee) [reply src/components/Highlighter.vue]: Thanks for the explanation @Kocal @Haroenv 
This is tricky 😅

Comment (francoischalifour) [reply src/components/Highlighter.vue]: @Haroenv Since this fix isn't straightforward, can add a comment in the code that explains what you described in https://github.com/algolia/vue-instantsearch/pull/827#discussion_r463560724 including the Vue issue?

Comment (Haroenv) [reply src/components/Highlighter.vue]: Good call. Since you can't leave a comment in that place (you'd change the rendering), I found an alternative solution, where you can leave a comment

File: src/util/parseAlgoliaHit.js [hunk 3]
```diff
@@ -39,7 +39,10 @@ function parseHighlightedAttribute({ preTag, postTag, highlightedValue = '' }) {
 
       if (splitByPostTag[1] !== '') {
         elements.push({
-          value: splitByPostTag[1],
+          // Vue removes nodes which are just a single space (vuejs/vue#9208),
```
Comment (Haroenv) [inline src/util/parseAlgoliaHit.js:42]: is this what you expected @francoischalifour?

Comment (francoischalifour) [reply src/util/parseAlgoliaHit.js:42]: Yep, thank you!
